/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.linguagem.prog1;

import java.awt.Color;
import javafx.scene.control.ProgressBar;

/**
 *
 * @author guilh
 */
public class Tela extends javax.swing.JFrame {
    DadosRandom dadosCPU = new DadosRandom();
    DadosRandom dadosMemoria = new DadosRandom();
    DadosRandom dadosDisco = new DadosRandom();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        PBarCPU = new javax.swing.JProgressBar();
        PBarMemoria = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        mediaCPU = new javax.swing.JLabel();
        minCPU = new javax.swing.JLabel();
        maxMemoria = new javax.swing.JLabel();
        minMemoria = new javax.swing.JLabel();
        maxCPU = new javax.swing.JLabel();
        mediaMemoria = new javax.swing.JLabel();
        PBarDisco = new javax.swing.JProgressBar();
        minDisco = new javax.swing.JLabel();
        maxDisco = new javax.swing.JLabel();
        mediaDisco = new javax.swing.JLabel();
        btnCalculo = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Média: 0%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        lblMemoria.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMemoria.setForeground(new java.awt.Color(255, 153, 51));
        lblMemoria.setText("Memória: 0%");

        lblCPU.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(255, 153, 51));
        lblCPU.setText("CPU: 0%");

        lblDisco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(255, 153, 51));
        lblDisco.setText("Disco: 0%");

        PBarCPU.setBackground(new java.awt.Color(0, 0, 0));

        PBarMemoria.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Uso de CPU Memória e Disco");

        mediaCPU.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mediaCPU.setText("Média: 0%");

        minCPU.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        minCPU.setText("Min: 0%");

        maxMemoria.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        maxMemoria.setText("Max: 0%");

        minMemoria.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        minMemoria.setText("Min: 0%");

        maxCPU.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        maxCPU.setText("Max: 0%");

        mediaMemoria.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mediaMemoria.setText("Média: 0%");

        PBarDisco.setBackground(new java.awt.Color(0, 0, 0));

        minDisco.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        minDisco.setText("Min: 0%");

        maxDisco.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        maxDisco.setText("Max: 0%");

        mediaDisco.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mediaDisco.setText("Média: 0%");

        btnCalculo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCalculo.setForeground(new java.awt.Color(255, 153, 0));
        btnCalculo.setText("Fazer calculo dos usos de CPU Memória e Disco");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisco)
                    .addComponent(lblMemoria)
                    .addComponent(lblCPU)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(minCPU)
                            .addGap(156, 156, 156)
                            .addComponent(mediaCPU)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxCPU))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(minDisco)
                            .addGap(158, 158, 158)
                            .addComponent(mediaDisco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxDisco))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(minMemoria)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mediaMemoria)
                            .addGap(149, 149, 149)
                            .addComponent(maxMemoria))
                        .addComponent(PBarCPU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PBarMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PBarDisco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addComponent(lblCPU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minCPU)
                    .addComponent(mediaCPU)
                    .addComponent(maxCPU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBarCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMemoria)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minMemoria)
                    .addComponent(maxMemoria)
                    .addComponent(mediaMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minDisco)
                    .addComponent(maxDisco)
                    .addComponent(mediaDisco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
        
        
        dadosCPU.aleatorio();
        dadosMemoria.aleatorio();
        dadosDisco.aleatorio();
        dadosCPU.maximo();
        dadosDisco.maximo();
        dadosMemoria.maximo();
        dadosCPU.minimo();
        dadosDisco.minimo();
        dadosMemoria.minimo();
        dadosCPU.contador();
        dadosCPU.media();
        dadosDisco.contador();
        dadosDisco.media();
        dadosMemoria.contador();
        dadosMemoria.media();
        PBarCPU.setValue(dadosCPU.dados3);
        lblCPU.setText(String.format("CPU: %d%%", dadosCPU.dados3));
        maxCPU.setText(String.format("Max: %d%%", dadosCPU.maximo));
        minCPU.setText(String.format("Min: %d%%", dadosCPU.minimo));
        mediaCPU.setText(String.format("Média: %d%%", dadosCPU.media));
        PBarMemoria.setValue(dadosMemoria.dados3);
        lblMemoria.setText(String.format("Memória: %d%%", dadosMemoria.dados3));
        maxMemoria.setText(String.format("Max: %d%%", dadosMemoria.maximo));
        minMemoria.setText(String.format("Min: %d%%", dadosMemoria.minimo));
        mediaMemoria.setText(String.format("Média: %d%%", dadosMemoria.media));
        PBarDisco.setValue(dadosDisco.dados3);
        lblDisco.setText(String.format("Disco: %d%%", dadosDisco.dados3));
        maxDisco.setText(String.format("Max: %d%%", dadosDisco.maximo));
        minDisco.setText(String.format("Min: %d%%", dadosDisco.minimo));
        mediaDisco.setText(String.format("Média: %d%%", dadosDisco.media));
        
    }//GEN-LAST:event_btnCalculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar PBarCPU;
    private javax.swing.JProgressBar PBarDisco;
    private javax.swing.JProgressBar PBarMemoria;
    private javax.swing.JButton btnCalculo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel maxCPU;
    private javax.swing.JLabel maxDisco;
    private javax.swing.JLabel maxMemoria;
    private javax.swing.JLabel mediaCPU;
    private javax.swing.JLabel mediaDisco;
    private javax.swing.JLabel mediaMemoria;
    private javax.swing.JLabel minCPU;
    private javax.swing.JLabel minDisco;
    private javax.swing.JLabel minMemoria;
    // End of variables declaration//GEN-END:variables
}
